# Methods

```{r , include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)

# clear environment
rm(list=ls())

# load packages
library(bookdown)
library(tinytex)
library(tidyverse)
library(googlesheets4)
library(lubridate)
library(readr)
library(readxl)
library(writexl)
library(hms)
library(plotly)
library(DT)
library(xlsx)
library(leaflet)
library(DT)
library(ggpubr)
library(plotrix)
library(packrat)
library(foreign)

# set plotting themes

## geom_col plots theme
col_theme <- theme(axis.title = element_text(size = 14, face = "bold"),
                   strip.text = element_text(size = 14, face = "bold"),
                   legend.title = element_text(size = 14, face = "bold"),
                   legend.text = element_text(size = 14),
                   axis.text = element_text(size = 14))

## geom_points plots theme
points_theme <- theme(axis.title = element_text(size = 14, face = "bold"),
                   strip.text = element_text(size = 14, face = "bold"),
                   legend.title = element_text(size = 14, face = "bold"),
                   legend.text = element_text(size = 14),
                   axis.text = element_text(size = 11, face = "bold"),
                   title = element_text(size = 18))

# function to exclude multiple items per column
'%ni%' <- Negate('%in%')

# clarify select function
select <- dplyr::select
```

## Site selection

Fish trapping sites are identified using KWF's database and further prioritized using the following criteria:

-   Significant increase in protection of anadromous fish habitat through addition of new miles/acreage

-   Ability to provide significant revision and/or data corroboration for outdated catalog data

-   Alignment with trapping priorities of local resource managers as well as partnership efforts including those of Kenai Mountains to Sea (a prioritized corridor list can be found at <https://kenaiwatershed.org/science-inaction/mountains-to-sea/>) and Kenai Peninsula Fish Habitat Partnership (KPFHP)

-   Ease of accessibility via foot travel or all-terrain vehicle (ATV) based on travel time and ability to obtain private property access

-   Proportion of stream or lake adjacent to developed parcels 

-   Habitat with medium-high risk assessment rating using the KPFHP's "Freshwater Potential Threats Ranking Table"

-   Tributaries of the Kenai River experiencing recent exceedances for zinc

-   Ability to leverage efforts with local partnership funding provided by groups like the KP-CWMA for invasive elodea surveys by identifying sites that overlap with trapping priorities

-   Unassessed anadromous fish habitat located on tributaries or mainstem waterbodies supporting subsistence fisheries

The project study map may be accessed by following the link at [ArcGIS Online](https://kwf.maps.arcgis.com/apps/webappviewer/index.html?id=ef6e57e2b94c424780b71decf08d50da&extent=-16891358.3246%2C8496162.7219%2C-16658378.2624%2C8619532.0855%2C102100) or in the interactive figure below. Click on the symbol in the upper right hand corner to see the legend. Toggle layers on/off as needed.

<iframe width="800" height="600" frameborder="0" scrolling="no" allowfullscreen src="https://arcg.is/Kji4r">

</iframe>

Prior to minnow trap deployment, we obtained all necessary permits from ADF&G including the Aquatic Resource Permit (ARP). As required by the ARP, the ADF&G local Area Management Biologist was notified of trapping locations and timeframes before going into the field. We also obtained landowner permission for access to sites. Finally, trapping efforts for each day were strategically chosen based on proximity of sites so as to reduce drive and personnel time.

## Fish capture

We used minnow traps baited with salmon eggs as the primary capture methods for juvenile salmonids. We used commercial salmon eggs as bait and placed them in perforated 2-4 oz Whirl-Paks in order to prevent egg consumption by fish. We labeled traps with KWF contact information using brightly colored flagging tape. At the trapping location, we collected site photos and recorded the following on a datasheet: field technician initials, GPS coordinates of trap deployment site(s), and site drawings with pertinent notes regarding fish habitat. We used a minimum of one baited minnow trap, fully submerged in a discrete location, and properly secured to ensure retrieval. We recorded the date and time of deployment. While not exceeding 24 hours, we  allowed traps to soak overnight when feasible. Upon trap retrieval, we recorded the date and time and transferred the trap's contents into a bucket of water. We identified each fish to lowest feasible taxa and life stage. We recorded disposition; and in some cases recorded fork length to the nearest millimeter along with photos of identifying features. When completed, we placed fish in a recovery bucket. Once all fish recuperated successfully, we released them near the original trap location. We monitored data throughout the summer for unintended mortalities, and were prepared to cease sampling and contact the area management biologist should \>10% unintended collection mortality occur. We entered all data into the Aquatic Resource Permit spreadsheet provided by the ADF&G and will be submitting it with a written report to ADF&G at the conclusion of each permit year.

These data will be utilized to submit nominations for the inclusion of new miles or acres of fish habitat to the AWC as well as revision or corroboration of fish presence.

## Habitat connectivity

In some cases where maps indicated a strong likelihood of anadromous habitat yet we did not capture salmonids, we visited additional sites within the drainage where potential barriers to fish passage may exist such as road crossings or modified lake outlets. We photographed and recorded coordinates at these locations if potential fish barriers were apparent and submitted them to ADF&G for potential inclusion in the Fish Barriers catalog.
